# Generated by Django 5.2.8 on 2026-10-03 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('feature', 'Feature idea'), ('bug', 'Something is broken'), ('album', 'Wrong or missing album info'), ('other', 'Other')], default='feature', max_length=20)),
                ('message', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('new', 'New'), ('planned', 'Planned'), ('done', 'Done'), ('declined', "Won't do")], default='new', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
