# Generated by Django 5.2.8 on 2026-10-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='price',
        ),
    ]
