# Generated by Django 5.2.8 on 2026-10-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
