# Generated by Django 5.2.8 on 2026-10-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='album',
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='album_image/'),
        ),
    ]
