# Generated by Django 5.2.8 on 2026-10-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_rename_movie_review_album_alter_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
