# Generated by Django 5.2.8 on 2026-10-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
