# Generated by Django 5.2.8 on 2026-10-03 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mbid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='cover_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='album',
            name='mbid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, upload_to='album_image/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.artist'),
        ),
    ]
