# Generated by Django 5.2.8 on 2026-10-03 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_artist_album_cover_url_album_mbid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('album', 'user'), name='one_review_per_user_per_album'),
        ),
    ]
