# Generated by Django 5.2.8 on 2026-10-03 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_alter_artistreview_rating_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disc', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('length_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='albums.album')),
            ],
            options={
                'ordering': ['disc', 'position'],
            },
        ),
    ]
