# Generated by Django 5.2.8 on 2026-10-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_album_tracks_fetched_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistreview',
            name='comment',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=5000),
        ),
    ]
